---
driver:
  name: docker

provisioner:
  name: chef_solo
  roles_path: provision/chef/roles
  data_bags_path:  provision/chef/data_bags
  cookbook_path:
    - berks-cookbooks


platforms:
  - name: built
    driver_config:
      privileged: true
      image: tompscanlan/packerd
      platform: ubuntu


suites:
  - name: packerd
    driver_config:
      dockerfile: kitchen-dockerfile
