---
driver:
  name: docker

provisioner:
  name: chef_solo
  roles_path: provision/chef/roles
  data_bags_path:  provision/chef/data_bags
  cookbook_path:
    - provision/chef/cookbooks
    - provision/chef/vendor-cookbooks
  # you can set these to a valid proxy if
  # running tests behind a proxy
  http_proxy: http://kbs316:Chapstacio7@proxy.kdc.capitalone.com:8099
  https_proxy: http://kbs316:Chapstacio7@proxy.kdc.capitalone.com:8099


platforms:
  - name: ubuntu
    driver_config:
      privileged: true
      image: ubuntu:trusty
      http_proxy: http://kbs316:Chapstacio7@proxy.kdc.capitalone.com:8099
      https_proxy: http://kbs316:Chapstacio7@proxy.kdc.capitalone.com:8099
  - name: built
    driver_config:
      privileged: true
      image: tompscanlan/ubuntu-packerd
      platform: ubuntu


suites:
  - name: packerd
    run_list:
      - role[packerd]

