swagger: "2.0"
info:
  description: REST interface to packer
  title: packerd
  version: 0.0.2
consumes:
- application/json
produces:
- application/json
schemes:
- http
- https
paths:
  /build:
    post:
      description: trigger a packer build for a particular git repository
      operationId: runBuild
      tags:
        - command
      parameters:
        - name: buildrequest
          description: a representaion of the build request
          in: body
          required: true
          schema:
            $ref: "#/definitions/buildrequest"
      responses:
        202:
          description: Accepted the request. Returns a link to the queued buildresponse
          schema:
            type: array
            items:
              $ref: "#/definitions/link"
        400:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /build/queue:
    get:
      description: get a list of links to all build requests
      operationId: getBuildList
      tags:
        - informational
      responses:
        200:
          description: list of links to the all build requests
          schema:
            type: array
            items:
              $ref: "#/definitions/link"
        204:
          description: no buildrequests exist
        400:
          description: generic error response
          schema:
            $ref: "#/definitions/error"

  /build/queue/{id}:
    get:
      description: get a specific build request
      operationId: getBuildListById
      tags:
        - informational
      parameters:
        - name: id
          description: uuid for the build
          in: path
          type: string
          required: true
          minLength: 36
          maxLength: 36
      responses:
        200:
          description: returns a build status
          schema:
            $ref: "#/definitions/buildrequest"
        400:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /build/responses/{id}:
    get:
      description: get all responses for this build id
      operationId: getBuildResponseById
      tags:
        - informational
      parameters:
        - name: id
          description: uuid for the build request
          in: path
          type: string
          required: true
          minLength: 36
          maxLength: 36
      responses:
        200:
          description: returns list of links to build responses for the build request id
          schema:
            type: array
            items:
              $ref: "#/definitions/link"
        400:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /build/responses/{id}/{buildnumber}:
    get:
      description: Get full detail of the response for a given build
      operationId: getBuildResponseByIDAndBuildNumber
      tags:
        - informational
      parameters:
        - name: id
          description: uuid for the build
          in: path
          type: string
          required: true
          minLength: 36
          maxLength: 36
        - name: buildnumber
          description: Each buildrequest may be re-run, this identifies which run
          in: path
          type: int64
          required: true
      responses:
        200:
          description: returns a build status
          schema:
              $ref: "#/definitions/buildresponse"
        400:
          description: generic error response
          schema:
            $ref: "#/definitions/error"

  /build/responses/{id}/{buildnumber}/stages:
    get:
      description: get all the stages of a specific build response
      operationId: getBuildStagesByIdBuildNumber
      tags:
        - informational
      parameters:
        - name: id
          description: uuid for the response
          in: path
          type: string
          required: true
          minLength: 36
          maxLength: 36
        - name: buildnumber
          description: Each buildrequest may be re-run, this identifies which run
          in: path
          type: int64
          required: true
      responses:
        200:
          description: list of links to the all stages
          schema:
            type: array
            items:
              $ref: "#/definitions/link"
        400:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /build/responses/{id}/{buildnumber}/stages/{stagename}:
    get:
      description: get all the stages of a specific build response
      operationId: getBuildStageByName
      tags:
        - informational
      parameters:
        - name: id
          description: uuid for the response
          in: path
          type: string
          required: true
          minLength: 36
          maxLength: 36
        - name: buildnumber
          description: Each buildrequest may be re-run, this identifies which run
          in: path
          type: int64
          required: true
        - name: stagename
          description: name of the stage
          in: path
          type: string
          required: true
          minLength: 1
          maxLength: 64         
      responses:
        200:
          description: detail of specific stage
          schema:
            $ref: "#/definitions/buildstage"
        400:
          description: generic error response
          schema:
            $ref: "#/definitions/error"

  /health:
    get:
      operationId: getHealth
      description: get health of the service
      tags:
        - informational
      responses:
        200:
          description: health of the service
          schema:
            $ref: "#/definitions/health"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
definitions:
  variable:
    description: one set of key=value to be passed to the packer build
    type: object
    required:
      - key
      - value
    properties:
      key:
       type: string
      value:
        type: string
  variables:
    description: list of vars
    type: array
    items:
      $ref: '#/definitions/variable'
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  buildresponse:
    type: object
    properties:
      buildrequestid:
        type: string
        description: uuid of the build request triggering this response
      id:
        type: string
        description: uuid of this response
      buildstages:
        type: array
        items:
          $ref: "#/definitions/buildstage"
      buildrequest:
        description: link to the build request
        items:
          $ref: "#/definitions/link"
      images:
        description: local image ids
        type: array
        items:
          type: string
      artifacts:
        description: url to remote artifact
        type: array
        items:
          $ref: "#/definitions/link"
      status:
        description: status of the build
        type: string
      eta:
        description: estimated seconds from now that the build will be completed.  Used to direct when you should check back
        type: integer
        format: int32
  buildrequest:
    required:
      - giturl
    properties:
      id:
        description: uuid of this request
        type: string
      buildonly:
        type: string
        description: only build the given builds by name, comma seperated
      buildvars:
        $ref: "#/definitions/variables"
      giturl:
        description: url to the git repo containing a packer config
        type: string
      templatepath:
        description: path within the giturl repo to the packer config.  defaults to /packer.json
        type: string
      branch:
        description: git branch checkout
        type: string
      localpath:
        description: not settable
        type: string
      responses:
        description: list of response ids generated for this build, a build that is retried may have more than one response
        type: array
        items:
          type: string
      responselinks:
        description: links to build responses
        type: array
        items:
          $ref: "#/definitions/link"
  buildstage:
    type: object
    properties:
      name:
        type: string
      status:
        type: string
        enum:
          - pending
          - running
          - failed
          - complete
      log:
        type: string
      start:
        type: string
        format: date-time
      end:
        type: string
        format: date-time
  link:
    type: object
    readOnly: true
    properties:
      rel:
        type: string
      href:
        type: string
        format: url
  health:
    type: object
    required:
      - status
      - diskpercentfull
    properties:
      status:
        type: string
      diskpercentfull:
        type: integer
        format: int
      goroutines:
        type: integer
        format: uint64

