package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.kdc.capitalone.com/kbs316/packerd/restapi/operations/command"
	"github.kdc.capitalone.com/kbs316/packerd/restapi/operations/informational"
)

// NewPackerdAPI creates a new Packerd instance
func NewPackerdAPI(spec *loads.Document) *PackerdAPI {
	o := &PackerdAPI{
		spec:            spec,
		handlers:        make(map[string]map[string]http.Handler),
		formats:         strfmt.Default,
		defaultConsumes: "application/json",
		defaultProduces: "application/json",
		ServerShutdown:  func() {},
	}

	return o
}

/*PackerdAPI REST interface to packer */
type PackerdAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// InformationalGetHealthHandler sets the operation handler for the get health operation
	InformationalGetHealthHandler informational.GetHealthHandler
	// InformationalGetPackerLogByIDHandler sets the operation handler for the get packer log by Id operation
	InformationalGetPackerLogByIDHandler informational.GetPackerLogByIDHandler
	// InformationalGetQueueHandler sets the operation handler for the get queue operation
	InformationalGetQueueHandler informational.GetQueueHandler
	// InformationalGetQueueByIDHandler sets the operation handler for the get queue by Id operation
	InformationalGetQueueByIDHandler informational.GetQueueByIDHandler
	// InformationalGetQueueTestLogByIDHandler sets the operation handler for the get queue test log by Id operation
	InformationalGetQueueTestLogByIDHandler informational.GetQueueTestLogByIDHandler
	// CommandRunBuildHandler sets the operation handler for the run build operation
	CommandRunBuildHandler command.RunBuildHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup
}

// SetDefaultProduces sets the default produces media type
func (o *PackerdAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *PackerdAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// DefaultProduces returns the default produces media type
func (o *PackerdAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *PackerdAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *PackerdAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *PackerdAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the PackerdAPI
func (o *PackerdAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.InformationalGetHealthHandler == nil {
		unregistered = append(unregistered, "informational.GetHealthHandler")
	}

	if o.InformationalGetPackerLogByIDHandler == nil {
		unregistered = append(unregistered, "informational.GetPackerLogByIDHandler")
	}

	if o.InformationalGetQueueHandler == nil {
		unregistered = append(unregistered, "informational.GetQueueHandler")
	}

	if o.InformationalGetQueueByIDHandler == nil {
		unregistered = append(unregistered, "informational.GetQueueByIDHandler")
	}

	if o.InformationalGetQueueTestLogByIDHandler == nil {
		unregistered = append(unregistered, "informational.GetQueueTestLogByIDHandler")
	}

	if o.CommandRunBuildHandler == nil {
		unregistered = append(unregistered, "command.RunBuildHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *PackerdAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *PackerdAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *PackerdAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *PackerdAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *PackerdAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

func (o *PackerdAPI) initHandlerCache() {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/health"] = informational.NewGetHealth(o.context, o.InformationalGetHealthHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/queue/{id}/buildlog"] = informational.NewGetPackerLogByID(o.context, o.InformationalGetPackerLogByIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/queue"] = informational.NewGetQueue(o.context, o.InformationalGetQueueHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/queue/{id}"] = informational.NewGetQueueByID(o.context, o.InformationalGetQueueByIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/queue/{id}/testlog"] = informational.NewGetQueueTestLogByID(o.context, o.InformationalGetQueueTestLogByIDHandler)

	if o.handlers["POST"] == nil {
		o.handlers[strings.ToUpper("POST")] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/build"] = command.NewRunBuild(o.context, o.CommandRunBuildHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *PackerdAPI) Serve(builder middleware.Builder) http.Handler {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}

	return o.context.APIHandler(builder)
}
