package informational

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetQueueByIDHandlerFunc turns a function with the right signature into a get queue by Id handler
type GetQueueByIDHandlerFunc func(GetQueueByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetQueueByIDHandlerFunc) Handle(params GetQueueByIDParams) middleware.Responder {
	return fn(params)
}

// GetQueueByIDHandler interface for that can handle valid get queue by Id params
type GetQueueByIDHandler interface {
	Handle(GetQueueByIDParams) middleware.Responder
}

// NewGetQueueByID creates a new http.Handler for the get queue by Id operation
func NewGetQueueByID(ctx *middleware.Context, handler GetQueueByIDHandler) *GetQueueByID {
	return &GetQueueByID{Context: ctx, Handler: handler}
}

/*GetQueueByID swagger:route GET /queue/{id} informational getQueueById

get status of a specific queued build request

*/
type GetQueueByID struct {
	Context *middleware.Context
	Handler GetQueueByIDHandler
}

func (o *GetQueueByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetQueueByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
