package informational

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetQueueTestLogByIDHandlerFunc turns a function with the right signature into a get queue test log by Id handler
type GetQueueTestLogByIDHandlerFunc func(GetQueueTestLogByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetQueueTestLogByIDHandlerFunc) Handle(params GetQueueTestLogByIDParams) middleware.Responder {
	return fn(params)
}

// GetQueueTestLogByIDHandler interface for that can handle valid get queue test log by Id params
type GetQueueTestLogByIDHandler interface {
	Handle(GetQueueTestLogByIDParams) middleware.Responder
}

// NewGetQueueTestLogByID creates a new http.Handler for the get queue test log by Id operation
func NewGetQueueTestLogByID(ctx *middleware.Context, handler GetQueueTestLogByIDHandler) *GetQueueTestLogByID {
	return &GetQueueTestLogByID{Context: ctx, Handler: handler}
}

/*GetQueueTestLogByID swagger:route GET /queue/{id}/testlog informational getQueueTestLogById

get the kitchen test log from a specific queued build request

*/
type GetQueueTestLogByID struct {
	Context *middleware.Context
	Handler GetQueueTestLogByIDHandler
}

func (o *GetQueueTestLogByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetQueueTestLogByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
