package informational

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/tompscanlan/packerd/models"
)

/*GetBuildResponseByIDAndBuildNumberOK returns a build status

swagger:response getBuildResponseByIdAndBuildNumberOK
*/
type GetBuildResponseByIDAndBuildNumberOK struct {

	// In: body
	Payload *models.Buildresponse `json:"body,omitempty"`
}

// NewGetBuildResponseByIDAndBuildNumberOK creates GetBuildResponseByIDAndBuildNumberOK with default headers values
func NewGetBuildResponseByIDAndBuildNumberOK() *GetBuildResponseByIDAndBuildNumberOK {
	return &GetBuildResponseByIDAndBuildNumberOK{}
}

// WithPayload adds the payload to the get build response by Id and build number o k response
func (o *GetBuildResponseByIDAndBuildNumberOK) WithPayload(payload *models.Buildresponse) *GetBuildResponseByIDAndBuildNumberOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get build response by Id and build number o k response
func (o *GetBuildResponseByIDAndBuildNumberOK) SetPayload(payload *models.Buildresponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBuildResponseByIDAndBuildNumberOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetBuildResponseByIDAndBuildNumberBadRequest generic error response

swagger:response getBuildResponseByIdAndBuildNumberBadRequest
*/
type GetBuildResponseByIDAndBuildNumberBadRequest struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBuildResponseByIDAndBuildNumberBadRequest creates GetBuildResponseByIDAndBuildNumberBadRequest with default headers values
func NewGetBuildResponseByIDAndBuildNumberBadRequest() *GetBuildResponseByIDAndBuildNumberBadRequest {
	return &GetBuildResponseByIDAndBuildNumberBadRequest{}
}

// WithPayload adds the payload to the get build response by Id and build number bad request response
func (o *GetBuildResponseByIDAndBuildNumberBadRequest) WithPayload(payload *models.Error) *GetBuildResponseByIDAndBuildNumberBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get build response by Id and build number bad request response
func (o *GetBuildResponseByIDAndBuildNumberBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBuildResponseByIDAndBuildNumberBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
