package informational

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/tompscanlan/packerd/models"
)

/*GetBuildResponseByIDOK returns list of links to build responses for the build request id

swagger:response getBuildResponseByIdOK
*/
type GetBuildResponseByIDOK struct {

	// In: body
	Payload []*models.Link `json:"body,omitempty"`
}

// NewGetBuildResponseByIDOK creates GetBuildResponseByIDOK with default headers values
func NewGetBuildResponseByIDOK() *GetBuildResponseByIDOK {
	return &GetBuildResponseByIDOK{}
}

// WithPayload adds the payload to the get build response by Id o k response
func (o *GetBuildResponseByIDOK) WithPayload(payload []*models.Link) *GetBuildResponseByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get build response by Id o k response
func (o *GetBuildResponseByIDOK) SetPayload(payload []*models.Link) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBuildResponseByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetBuildResponseByIDBadRequest generic error response

swagger:response getBuildResponseByIdBadRequest
*/
type GetBuildResponseByIDBadRequest struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBuildResponseByIDBadRequest creates GetBuildResponseByIDBadRequest with default headers values
func NewGetBuildResponseByIDBadRequest() *GetBuildResponseByIDBadRequest {
	return &GetBuildResponseByIDBadRequest{}
}

// WithPayload adds the payload to the get build response by Id bad request response
func (o *GetBuildResponseByIDBadRequest) WithPayload(payload *models.Error) *GetBuildResponseByIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get build response by Id bad request response
func (o *GetBuildResponseByIDBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBuildResponseByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
