package informational

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBuildStageByNameParams creates a new GetBuildStageByNameParams object
// with the default values initialized.
func NewGetBuildStageByNameParams() GetBuildStageByNameParams {
	var ()
	return GetBuildStageByNameParams{}
}

// GetBuildStageByNameParams contains all the bound params for the get build stage by name operation
// typically these are obtained from a http.Request
//
// swagger:parameters getBuildStageByName
type GetBuildStageByNameParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Each buildrequest may be re-run, this identifies which run
	  Required: true
	  In: path
	*/
	Buildnumber int64
	/*uuid for the response
	  Required: true
	  Max Length: 36
	  Min Length: 36
	  In: path
	*/
	ID string
	/*name of the stage
	  Required: true
	  Max Length: 64
	  Min Length: 1
	  In: path
	*/
	Stagename string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetBuildStageByNameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rBuildnumber, rhkBuildnumber, _ := route.Params.GetOK("buildnumber")
	if err := o.bindBuildnumber(rBuildnumber, rhkBuildnumber, route.Formats); err != nil {
		res = append(res, err)
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	rStagename, rhkStagename, _ := route.Params.GetOK("stagename")
	if err := o.bindStagename(rStagename, rhkStagename, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBuildStageByNameParams) bindBuildnumber(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("buildnumber", "path", "int64", raw)
	}
	o.Buildnumber = value

	return nil
}

func (o *GetBuildStageByNameParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.ID = raw

	if err := o.validateID(formats); err != nil {
		return err
	}

	return nil
}

func (o *GetBuildStageByNameParams) validateID(formats strfmt.Registry) error {

	if err := validate.MinLength("id", "path", string(o.ID), 36); err != nil {
		return err
	}

	if err := validate.MaxLength("id", "path", string(o.ID), 36); err != nil {
		return err
	}

	return nil
}

func (o *GetBuildStageByNameParams) bindStagename(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Stagename = raw

	if err := o.validateStagename(formats); err != nil {
		return err
	}

	return nil
}

func (o *GetBuildStageByNameParams) validateStagename(formats strfmt.Registry) error {

	if err := validate.MinLength("stagename", "path", string(o.Stagename), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("stagename", "path", string(o.Stagename), 64); err != nil {
		return err
	}

	return nil
}
