package informational

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/tompscanlan/packerd/models"
)

/*GetBuildStagesByIDBuildNumberOK list of links to the all stages

swagger:response getBuildStagesByIdBuildNumberOK
*/
type GetBuildStagesByIDBuildNumberOK struct {

	// In: body
	Payload []*models.Link `json:"body,omitempty"`
}

// NewGetBuildStagesByIDBuildNumberOK creates GetBuildStagesByIDBuildNumberOK with default headers values
func NewGetBuildStagesByIDBuildNumberOK() *GetBuildStagesByIDBuildNumberOK {
	return &GetBuildStagesByIDBuildNumberOK{}
}

// WithPayload adds the payload to the get build stages by Id build number o k response
func (o *GetBuildStagesByIDBuildNumberOK) WithPayload(payload []*models.Link) *GetBuildStagesByIDBuildNumberOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get build stages by Id build number o k response
func (o *GetBuildStagesByIDBuildNumberOK) SetPayload(payload []*models.Link) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBuildStagesByIDBuildNumberOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetBuildStagesByIDBuildNumberBadRequest generic error response

swagger:response getBuildStagesByIdBuildNumberBadRequest
*/
type GetBuildStagesByIDBuildNumberBadRequest struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBuildStagesByIDBuildNumberBadRequest creates GetBuildStagesByIDBuildNumberBadRequest with default headers values
func NewGetBuildStagesByIDBuildNumberBadRequest() *GetBuildStagesByIDBuildNumberBadRequest {
	return &GetBuildStagesByIDBuildNumberBadRequest{}
}

// WithPayload adds the payload to the get build stages by Id build number bad request response
func (o *GetBuildStagesByIDBuildNumberBadRequest) WithPayload(payload *models.Error) *GetBuildStagesByIDBuildNumberBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get build stages by Id build number bad request response
func (o *GetBuildStagesByIDBuildNumberBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBuildStagesByIDBuildNumberBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
