package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*Buildrequest buildrequest

swagger:model buildrequest
*/
type Buildrequest struct {

	/* git branch checkout
	 */
	Branch string `json:"branch,omitempty"`

	/* only build the given builds by name, comma seperated
	 */
	Buildonly string `json:"buildonly,omitempty"`

	/* buildvars
	 */
	Buildvars Variables `json:"buildvars,omitempty"`

	/* url to the git repo containing a packer config

	Required: true
	*/
	Giturl *string `json:"giturl"`

	/* uuid of this request
	 */
	ID string `json:"id,omitempty"`

	/* not settable
	 */
	Localpath string `json:"localpath,omitempty"`

	/* links to build responses
	 */
	Responselinks []*Link `json:"responselinks,omitempty"`

	/* list of response ids generated for this build, a build that is retried may have more than one response
	 */
	Responses []string `json:"responses,omitempty"`

	/* path within the giturl repo to the packer config.  defaults to /packer.json
	 */
	Templatepath string `json:"templatepath,omitempty"`
}

// Validate validates this buildrequest
func (m *Buildrequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGiturl(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateResponselinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateResponses(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Buildrequest) validateGiturl(formats strfmt.Registry) error {

	if err := validate.Required("giturl", "body", m.Giturl); err != nil {
		return err
	}

	return nil
}

func (m *Buildrequest) validateResponselinks(formats strfmt.Registry) error {

	if swag.IsZero(m.Responselinks) { // not required
		return nil
	}

	for i := 0; i < len(m.Responselinks); i++ {

		if swag.IsZero(m.Responselinks[i]) { // not required
			continue
		}

		if m.Responselinks[i] != nil {

			if err := m.Responselinks[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *Buildrequest) validateResponses(formats strfmt.Registry) error {

	if swag.IsZero(m.Responses) { // not required
		return nil
	}

	return nil
}
